### ISSUE TITLE
11/6 MVPレビュー依頼初回提出

### ISSUE THREAD

**Issue by R-Tok** [R-Tok/MyApp#21]

**Comment by R-Tok** [comment]
## 各種情報
サービスの概要とMVPで検証する事柄：
【概要】
"メジャーではないけれどオススメしたいローカルスポット"になるべく特化して、ユーザーのお出かけ記録を共有するCGMサービス。
投稿者にとっては旅の記録やシェア、閲覧者にとっては情報収集ができる。
旅慣れしている人や、一人旅や街歩きが好きな人を対象ユーザーとする想定。

【検証項目】
・ユーザー登録・ログインができること。
・GoogleMapAPIを使ったスポット登録ができること。
登録完了後は投稿作成画面へと遷移し、そこでは画像ファイルを添付して投稿ができること。
・投稿状況に応じて、「投稿状況マップ」の色塗りが変動すること。
・投稿者アイコンや名前をクリックすることで、ユーザー情報ページが表示されること。それが自身のページの場合、プロフィール編集ができること。

サービス名：LocalTripHub
サービスURL：https://localtriphub.com
URL(GitHub)：https://github.com/R-Tok/LocalTripHub


## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] プロフィール編集機能
- [x] スポット登録機能
- [ ] スポット検索機能　　→MVP後の実装とする
- [x] 新規投稿・編集・削除機能
- [ ] ブックマーク・リスト登録機能　　→MVP後の実装とする
- [x] 投稿状況の色分けマップ表示機能
- [x] 投稿一覧画面にGoogleMapAPI導入


## READMEレビュー時から変更した機能
### MVPリリースから除外
・スポット検索機能：
GoogleMapを用いて登録スポット一覧画面を作成したため、スポット名検索機能は現時点で必須ではないと判断した。
・ユーザー毎に、ブックマークした投稿をリスト化およびリスト編集する機能：
MVP時点ではブックマーク機能までは不要とした。ただしこれを実装してから本リリースとしたい。

### MVP時で追加実装
・スポット登録画面にGoogleMapAPI導入：
スポットの新規登録画面でGoogleMapAPIを導入し、直感的に操作できるようにした。
①検索ボックスまたは地図上をクリックすることで、座標を決める。
②決めた座標に基づいて、緯度経度や市町村情報を自動入力する。


## サービスイメージがわかるようなスクリーンショット等
### ・投稿状況に応じた、都道府県・市町村の色塗りマップ
[![Image from Gyazo](https://i.gyazo.com/f87416b155f0ea2a855f9765ba002882.png)](https://gyazo.com/f87416b155f0ea2a855f9765ba002882)

### ・GoogleMapを使って新規スポット登録
[![Image from Gyazo](https://i.gyazo.com/eff38d4a3b5da79fb59a4b04ff89c4f4.png)](https://gyazo.com/eff38d4a3b5da79fb59a4b04ff89c4f4)

### ・スポット別に投稿一覧を表示することもできる。
[![Image from Gyazo](https://i.gyazo.com/1b8166326fca636b8d719162f4bf948b.png)](https://gyazo.com/1b8166326fca636b8d719162f4bf948b)

**Comment by kashiwagi-rena** [comment]
下記機能について確認ができませんでした。
ご確認の上、必要であれば修正等を行ってください。
もし実装できているのであれば、コメントに確認手順を詳しく記載してください。
上記いずれかのご対応の上、RUNTEQアプリから再提出してください。

---

SP画面の際にリロードするとエラー画面に遷移しました。
最初にスマフォで見る方もいるかもしれないため、エラー原因を突き止めて修正していただきたいです。


https://github.com/user-attachments/assets/632075a1-729f-42dc-a324-87fb63c36e4f

**Comment by R-Tok** [comment]
ご指摘いただきありがとうございました。以下の修正を行いました。
・`allow_browser versions: :modern` をコメントアウトすることでブラウザの制限を除去した。
・モバイル版のSafariで、端末の設定によっては予期しない背景色が設定されることを確認。
headタグ内に `<meta name="theme-color" content="#ffffff">` という記述をして、白色背景を指定した。

再度ご確認のほどよろしくお願い致します。

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください〜！

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
