### ISSUE TITLE
issueベースの開発　レビュー依頼

### ISSUE THREAD

**Issue by R-Tok** [R-Tok/MyApp#6]

**Comment by R-Tok** [comment]
■Webアプリの概要
ユーザーが住む街や旅先で出会った"メジャーではないけれどオススメしたいローカルスポット"になるべく特化して、お出かけ記録を共有するCGMサービス。
投稿者にとっては旅の記録や情報のシェア、閲覧者にとっては情報収集ができる。
対象ユーザーは、旅慣れしている人や、一人旅や街歩きが好きな人というイメージ。

基本機能①：投稿機能
お出かけスポットを新規登録し、旅行記録を投稿する。
“スポット”の登録情報は、スポット名・所在自治体・カテゴリ・緯度経度。
“投稿”の登録情報は、詳細(本文)、アクセス情報、画像登録。
他ユーザーが既に登録したスポットに対し、追加投稿することも可能とする。

基本機能②：地図色分け機能
投稿スポットの所在地について、都道府県や市町村地図が投稿数に応じて濃く塗られていく地図を表示する。
まだ色が薄い(投稿が少ない)エリアも、ユーザー間で投稿を増やしていくモチベーションにしてもらいたい。

基本機能③：投稿保存リスト機能
投稿ブックマーク用のリストをユーザーごとに複数作成できる。
ブックマーク機能により、指定した任意のリストへお気に入り投稿を保存する。

■1週間辺りの開発に向けられる時間
- 1週間あたり：20時間

■ProjectsのURL
https://github.com/users/R-Tok/projects/1/views/1?sumFields=%5B130914927%5D&hideItemsCount=false

■MVPリリースまで
- [x] rails new
- [ ] Fly.ioにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] プロフィール編集機能
- [ ] スポット登録機能
- [ ] スポット検索機能
- [ ] 新規投稿・編集・削除機能
- [ ] ブックマーク・リスト登録機能
- [ ] 投稿状況の色分けマップ表示機能
- [ ] 投稿一覧画面にGoogleMapAPI導入

■MVP後
- [ ] GoogleMapAPIの導入拡充(スポット登録画面)
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] ファビコン
- [ ] 独自ドメイン
- [ ] レスポンシブ対応
- [ ] RSpec


■MVPレビュー依頼予定日
予定日：2024年 11月 11日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- ブックマーク・リスト
